GET {{host}}/r/MTYzNjI1OTM2MDQyMQ HTTP/1.1
Accept-Version: 3
###
POST {{host}}/endpoints HTTP/1.1
###
GET {{host}}/endpoints HTTP/1.1
###
GET {{host}}/docs HTTP/1.1
###
GET {{host}}/openapi.json HTTP/1.1
###
GET {{host}}/endpoints/MTYzNjI1OTM2MDQyMQ HTTP/1.1
###
DELETE {{host}}/r/MTYzNjI1OTM2MDQyMQ?id=2&stuff=abcd HTTP/1.1
Accept-Version: 3
###
OPTIONS {{host}}/r/MTYzNjI1OTM2MDQyMQ?id=2&stuff=abcd HTTP/1.1
Accept-Version: 3
###
TRACE {{host}}/r/MTYzNjI1OTM2MDQyMQ?id=2&stuff=abcd HTTP/1.1
Accept-Version: 3
###
HEAD {{host}}/r/MTYzNjI1OTM2MDQyMQ?id=2&stuff=abcd HTTP/1.1
Accept-Version: 3
###
POST {{host}}/r/MTYzNjI1OTM2MDQyMQ?id=2&stuff=abcd HTTP/1.1
Accept-Version: 3
Content-Type: application/json

{
    "data": {
        "id": 1,
        "type": "extracts",
        "attributes": {
            "name": "Chris"
        }
    }
}
###
PUT {{host}}/r/MTYzNjI1OTM2MDQyMQ?id=2&stuff=abcd HTTP/1.1
Accept-Version: 3
Content-Type: application/json

{
    "data": {
        "id": 1,
        "type": "extracts",
        "attributes": {
            "name": "Chris"
        }
    }
}
###
PATCH {{host}}/r/MTYzNjI1OTM2MDQyMQ?id=2&stuff=abcd HTTP/1.1
Accept-Version: 3
Content-Type: application/json

{
    "data": {
        "id": 1,
        "type": "extracts",
        "attributes": {
            "name": "Chris"
        }
    }
}
###
GET {{host}}/endpoints/MTYzNjI1OTM2MDQyMQ/requests HTTP/1.1
###
GET {{host}}/requests HTTP/1.1
###
GET https://ennboo5c59dywcg.m.pipedream.net HTTP/1.1
###
POST {{host}}/r/MTYzNjI1OTM2MDQyMQ?id=2&stuff=abcd HTTP/1.1
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="pdf"; filename="anz_anz_first_free_days_visa.pdf"

< /home/chris/Desktop/GAMEBOX_EN.pdf
--WebAppBoundary--

###